from enum import Enum

class Status(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    NOT_FOUND = 'NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'

class AuthStatus(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    INVALID_TOKEN = 'INVALID_TOKEN'
    INVALID_USER = 'INVALID_USER'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_EMAIL = 'INVALID_EMAIL'
    INVALID_USERNAME = 'INVALID_USERNAME'
    INVALID_ROLE = 'INVALID_ROLE'
    INVALID_STATUS = 'INVALID_STATUS'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'

class Roles(Enum):
    ADMIN = 'ADMIN'
    USER = 'USER'

class OrderStatus(Enum):
    PROCESSING = 'PROCESSING'
    READY_FOR_PICKUP = 'READY_FOR_PICKUP'
    CHECKED_OUT = 'CHECKED_OUT'
    RETURNED = 'RETURNED'
    CANCELLED = 'CANCELLED'
    LOST = 'LOST'

