"""Add order_date column to orders table

Revision ID: 3106a3fd3744
Revises: cffa262f5169
Create Date: 2025-04-01 19:58:16.762495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106a3fd3744'
down_revision: Union[str, None] = 'cffa262f5169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
