"""Add order_date column to orders table

Revision ID: 565836f737dc
Revises: 3106a3fd3744
Create Date: 2025-04-01 20:14:20.375478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565836f737dc'
down_revision: Union[str, None] = '3106a3fd3744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'checkout_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'checkout_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
